
-- Generate tables
create table fees_rules (id bigint generated by default as identity, maximum_days integer not null, minimum_value decimal(20,2) not null, percentage_fee decimal(8,8), priority bigint not null, recurring_fixed_fee decimal(20,2), single_fixed_fee decimal(20,2), primary key (id));
create table transfer_scheduling (id bigint generated by default as identity, amount decimal(20,2) not null, fee decimal(20,2) not null, processing_date date not null, scheduling_date date not null, source_account varchar(6) not null, target_account varchar(6) not null, primary key (id));
alter table fees_rules add constraint UK6j8ah9wqfaxubcxe0c8tvc98s unique (priority, maximum_days, minimum_value);

-- Business rule
INSERT INTO FEES_RULES (priority, maximum_days, minimum_value, percentage_fee, single_fixed_fee, recurring_fixed_fee)
	VALUES	(100, 0, '0.00', '0.03', '3.00', NULL),
			(200, 10, '0.00',NULL, NULL, '12.00'),
			(300, 20, '0.00','0.08', NULL, NULL),
			(400, 30, '0.00','0.06', NULL, NULL),
			(500, 40, '0.00','0.04', NULL, NULL),
			(600, 2147483647, '100000.00','0.02', NULL, NULL);